#!/bin/bash

set -ex

export COMPILE_MIDAS_ADD_DEBUG_OPTIONS=no

cd /home/dlo001/midas-177v9/src/programs
echo Launching compilation on '${TRUE_HOST}' for platform '${ORDENV_PLAT}'
yes '' | head -n 17 | ./compile_all.sh

cd /fs/site4/eccc/cmd/a/dlo001/hall4/midas-177v9/tools/splitobs
make splitobs_${ORDENV_PLAT}

splitobs_pgm=midas.splitobs_${ORDENV_PLAT}-$(../../midas.version.sh).Abs
make install PGM=../../compiledir/midas_abs/${splitobs_pgm}

