#!/bin/bash
#
# Explanation that this is not part of the CMake workflow but is just a helper
# to save some typing.
#
# Basically there are two commands to know:
#
# 1. Configure a build directory.  Generate makefiles
#
#      cmake -S SOURCE_DIR -B BUILD_DIR [-DOPTION=VALUE ...]
#
#   The options are provided by the project maintainers to enable the users
#   to change aspects of the build process without needing to understand cmake.
#
#   This is also equivalent to doing
#
#      mkdir BUILD_DIR
#      cd BUILD_DIR
#      cmake SOURCE_DIR
#
# 2. Building the entire project or single targets
#
#      cmake --build BUILD_DIR [--target TARGET] [-- -j [N]]
#
#   this is exactly equivalent to CD'ing into BUILD_DIR and doing
#
#      make [-j N] [TARGET]
#

            cmake_command='cmake -S . -B ${build_dir}  "$@"'
      cmake_debug_command='cmake -S . -B ${build_dir}  -DCMAKE_BUILD_TYPE=Debug "$@"'
cmake_debug_extra_command='cmake -S . -B ${build_dir}  -DCMAKE_BUILD_TYPE=Debug -DEXTRA_CHECKS=ON "$@"'

  build_command='cmake --build ${build_dir} -- "$@"'
install_command='cmake --build ${build_dir} --target install -- "$@"'
package_command='cmake --build ${build_dir} --target package -- "$@"'
  clean_command='cmake --build ${build_dir} --target clean -- "$@"'

print_cado_help(){
  printf "Usage: cado COMMAND ..

Shortcuts for configuring and building ${this_project}.

\033[1mDESCRIPTION\033[0m:
    This project is configured using CMake.  To get started, you must first run
    one of the \`cado cmake*\` commands which will configure the project to be
    built following certain options described below.
    
    Once this is done, one of the other commands (build, work, package, clean)
    may be used build the project and possibly install it to the working
    directory

\033[1mCOMMANDS\033[0m:
  \033[4mconfiguration\033[0m:
    \033[1mcmake\033[0m:
        Generate Makefiles for building the project with installed RPN
        dependencies when at CMC, or with their sources outside CMC.
    \033[1mcmake-debug\033[0m:
        Generate Makefiles for compiling with debug flags. 
    \033[1mcmake-debug-extra\033[0m:
        Generate Makefiles for compiling with debug flags and extra checks.

  \033[4mbuilding\033[0m:
    Additional arguments will be passed to the build tool (make).  For example
    \`cado build -j\`
    \033[1mbuild\033[0m:
        Build the entire project
    \033[1mpackage\033[0m:
        Build the entire project and create an SSM package.
    \033[1mclean\033[0m:
        Clean all build artifacts (.o, .a, .so, and executables)
  
NOTE:
    - Because CMake supports and encourages out-of-tree builds, the equivalent of
      distclean target from the GNU standard is simply removing the build directory.

"
}

print_cado_short_help(){
  printf "cado COMMAND [...]

COMMANDS:
  configuration: (additional arguments forwarded to CMake)
    cmake: configure using installed RPN libraries at CMC
    cmake-debug: configure with debug flags (-DCMAKE_BUILD_TYPE=Debug)
    cmake-debug-extra:  configure with debug flags and extra compile-time checks (-DCMAKE_BUILD_TYPE=Debug -DEXTRA_CHECKS=ON)

  building: (Additional arguments forwarded to make (like -j))
    build: Build entire project
    install: Install binaries and scripts
    package: Build entire project, create SSM package
    clean: Delete build artifacts

See \`cado --help\` for more detailed info
"
}

if [[ -z $(eval echo \${MIDAS_SOURCE_DIR}) ]] ; then
    echo "$0: This convenience helper uses \${MIDAS_SOURCE_DIR} to set the cmake source directory,"
    echo "\${MIDAS_COMPILE_DIR_MAIN} for the build directory, and \${MIDAS_ABS_LEAFDIR}"
    echo "for the install directory, but the variables are not set.  This indicates that the"
    echo "src/config-cmake.dot.sh configuration file has not been called.  This is"
    echo "necessary for the build with or without this helper."
    exit 1
fi

if [[ $(realpath $PWD) != $(realpath $(eval echo \${MIDAS_SOURCE_DIR})) ]] ; then
  printf "$0: \033[1;31mERROR\033[0m: This command must be run from the top of the source code repository\n"
  exit 1
fi

if ! build_dir=$(realpath $(eval echo \${MIDAS_COMPILE_DIR_MAIN})) ; then
    echo "ERROR running true_path on '\${MIDAS_COMPILE_DIR_MAIN}'."
fi
echo "Using build directory '${build_dir}'"

name=$1
shift
cmd=""

case "${name}" in
                cmake) cmd=${cmake_command} ;;
          cmake-debug) cmd=${cmake_debug_command} ;;
    cmake-debug-extra) cmd=${cmake_debug_extra_command} ;;
                build) cmd=${build_command} ;;
              install) cmd=${install_command} ;;
              package) cmd=${package_command} ;;
                clean) cmd=${clean_command} ;;
          help|--help) print_cado_help ; exit 0 ;;
                   -h) print_cado_short_help ; exit 0 ;;
      '') printf "\033[1;31mERROR\033[0m: A command is required\n"; print_cado_short_help ; exit 1 ;;
      *)  printf "\033[1;31mERROR\033[0m: Unknown command '${name}', see \`cado help\`\n"; exit 1 ;;
esac

printf "$0: running '${name}' command:\n"
eval echo ${cmd}
eval ${cmd}

cmd_exit_code=$?
if [[ ${cmd_exit_code} == 0 ]] ; then
  printf "$0: Command '${name}' completed successfully:\n"
else
  printf "$0: Command '${name}' completed failed with code ${cmd_exit_code}:\n"
fi
eval echo ${cmd}
exit ${cmd_exit_code}
