#!/bin/bash

set -euo pipefail

typeset -r toplevel=${1:-$(git rev-parse --show-toplevel)}

typeset -r resourcesDir=${toplevel}/maestro/suites/midas_system_tests/resources

# select which file to use for resources.def
if [ "${TRUE_HOST}" = eccc-ppp1 -o "${TRUE_HOST}" = eccc-ppp2 -o "${TRUE_HOST}" = hare -o "${TRUE_HOST}" = brooks ]; then
    typeset -r  resources_file=resources.def_ppp12_xc40
elif [ "${TRUE_HOST}" = eccc-gpsc1 -o "${TRUE_HOST}" = eccc-ppp3 -o "${TRUE_HOST}" = eccc-ppp4 -o \
       "${TRUE_HOST}" = daley -o "${TRUE_HOST}" = banting -o "${TRUE_HOST}" = xc3 -o "${TRUE_HOST}" = xc4 ]; then
    typeset -r resources_file=resources.def_ppp34_xc50
elif [ "${TRUE_HOST}" = ppp5 -o "${TRUE_HOST}" = ppp6 -o "${TRUE_HOST}" = robert -o "${TRUE_HOST}" = underhill ]; then
    typeset -r resources_file=resources.def_hpcr-u2
elif [ "${TRUE_HOST}" = ppp7 -o "${TRUE_HOST}" = ppp8 -o "${TRUE_HOST}" = moira -o "${TRUE_HOST}" = conrad ]; then
    typeset -r resources_file=resources.def_hpcr-u3
else
    echo "set_resources_def.sh: Unknown TRUE_HOST: ${TRUE_HOST}"
    exit 1
fi

typeset -r currentDirectory=${PWD}

cd ${resourcesDir}
cat > resources.def <<EOF
#########################
## DO NOT EDIT THIS FILE!
## Instead, edit ${resourcesDir}/${resources_file}

EOF

cat ${resources_file} >> resources.def

cat >> resources.def <<EOF

## DO NOT EDIT THIS FILE!
########################
EOF

cd ${currentDirectory}
