
module obsFlags_mod
  ! MODULE obsFlags_mod (prefix='flg' category='8. Low-level utilities and constants')
  !
  !:Purpose:  Contains a list of all possible bit numbers used when setting or
  !           interpreting the bits for indicating the status of observations.
  !
  !           Note that the actual bit values stored in the public variables have
  !           an arbitrary offset added to them to help catch direct uses of
  !           hardcoded values when calling any of the routines in this module for
  !           checking, setting or clearing bits. The goal is to make it harder for
  !           people to avoid using the descriptive public variables for the bit
  !           numbers.
  !
  use obsSpaceData_mod
  use midasMpi_mod
  use utilities_mod
  use runtimeInfo_mod

  implicit none
  save
  private

  ! Public procedures
  public :: flg_flagIsOn, flg_flagIsOnFromRefValue
  public :: flg_setFlag, flg_resetFlag, flg_clearFlag
  public :: flg_refValueTobitNum

  ! Public variables (parameters)
  public :: flg_descrip

  ! Public variables for each possible bitNumber value
  integer, public, parameter :: flg_offset = 1000    ! Arbitary offset value
  integer, public, parameter :: flg_00           = 00 + flg_offset
  integer, public, parameter :: flg_01           = 01 + flg_offset
  integer, public, parameter :: flg_02erroneous  = 02 + flg_offset
  integer, public, parameter :: flg_03           = 03 + flg_offset
  integer, public, parameter :: flg_04doubtful   = 04 + flg_offset
  integer, public, parameter :: flg_05           = 05 + flg_offset
  integer, public, parameter :: flg_06biasCorr   = 06 + flg_offset
  integer, public, parameter :: flg_07rejVarious = 07 + flg_offset
  integer, public, parameter :: flg_08rejBlackL  = 08 + flg_offset
  integer, public, parameter :: flg_09rejBgck    = 09 + flg_offset
  integer, public, parameter :: flg_10rejIceGross= 10 + flg_offset
  integer, public, parameter :: flg_11rejSelect  = 11 + flg_offset
  integer, public, parameter :: flg_12seenByAnl  = 12 + flg_offset
  integer, public, parameter :: flg_13ompLevel1  = 13 + flg_offset
  integer, public, parameter :: flg_14ompLevel2  = 14 + flg_offset
  integer, public, parameter :: flg_15ompLevel3  = 15 + flg_offset
  integer, public, parameter :: flg_16rejOmP     = 16 + flg_offset
  integer, public, parameter :: flg_17rejVarQC   = 17 + flg_offset
  integer, public, parameter :: flg_18rejOro     = 18 + flg_offset
  integer, public, parameter :: flg_19rejLandSea = 19 + flg_offset
  integer, public, parameter :: flg_20           = 20 + flg_offset
  integer, public, parameter :: flg_21rejTooHigh = 21 + flg_offset
  integer, public, parameter :: flg_22           = 22 + flg_offset
  integer, public, parameter :: flg_23cloudyObs  = 23 + flg_offset
  integer, public, parameter :: flg_24simulatObs = 24 + flg_offset
  integer, public, parameter :: flg_25passiveObs = 25 + flg_offset

  integer,         parameter :: minBitValue = 0
  integer,         parameter :: maxBitValue = 25

  ! Interface for testing bit value
  interface flg_flagIsOn
    module procedure flg_flagIsOnFromObsData
    module procedure flg_flagIsOnFromFlagInt
    module procedure flg_flagsAreOnFromObsData
    module procedure flg_flagsAreOnFromFlagInt
  end interface flg_flagIsOn

  ! Interface for setting one or more bits
  interface flg_setFlag
    module procedure flg_setFlagFromObsData
    module procedure flg_setFlagsFromObsData
    module procedure flg_setFlagFromFlagInt
    module procedure flg_setFlagsFromFlagInt
  end interface flg_setFlag

  ! Interface for clearing bits
  interface flg_clearFlag
    module procedure flg_clearFlagFromObsData
    module procedure flg_clearFlagFromFlagInt
  end interface flg_clearFlag

  ! Interface for private routine to check validity of bit numbers
  interface checkBitNumberIsValid
    module procedure checkBitNumberIsValidScalar
    module procedure checkBitNumberIsValidArray
  end interface checkBitNumberIsValid


  ! Descriptions of all flag values, ordered by bitNumber
  character(len=33), parameter :: flg_descrip(minBitValue:maxBitValue) = &
                  ['DATA MODIFIED OR GEN BY ADE      ', & ! 00
                   'DATA EXCEEDS CLIMATE EXTREME     ', & ! 01
                   'ERRONEOUS DATA                   ', & ! 02
                   'POSSIBLY ERRONEOUS DATA          ', & ! 03
                   'DOUBTFUL DATA                    ', & ! 04
                   'INTERPOLATED DATA                ', & ! 05
                   'CORRECTED DATA (BIAS CORRECTED)  ', & ! 06
                   'SAT DATA REJECTED VARIOUS REASONS', & ! 07
                   'REJECTION BY BLACK LIST          ', & ! 08
                   'REJECTION BY BACKGROUND CHECK    ', & ! 09
                   'GENERATED BY OI (ICE GROSS CHECK)', & ! 10
                   'REJECTION BY SELECTION PROCESS   ', & ! 11
                   'DATA SEEN BY ANALYSIS            ', & ! 12
                   'O-P CHECK LEVEL 1                ', & ! 13
                   'O-P CHECK LEVEL 2                ', & ! 14
                   'O-P CHECK LEVEL 3                ', & ! 15
                   'REJECTION BY O-P CHECK           ', & ! 16
                   'REJECTION BY VARQC               ', & ! 17
                   'REJECTION BY OROGRAPHY CHECK     ', & ! 18
                   'REJECTION BY LAND-SEA MASK       ', & ! 19
                   'AIRCRAFT DATA REJECTED BY TRACKQC', & ! 20
                   'REJECTION DUE TO ABOVE MODEL TOP ', & ! 21
                   'REJECTION BY RAW TO BURP         ', & ! 22
                   'CLOUD AFFECTED RADIANCE          ', & ! 23
                   'SIMULATED OBSERVATION            ', & ! 24
                   'PASSIVE OBSERVATION              ']   ! 25

contains

  !--------------------------------------------------------------------------
  ! bitNumberIsValidScalar
  !--------------------------------------------------------------------------
  subroutine checkBitNumberIsValidScalar(bitNumber)
    !
    ! :Purpose: Check if a bit number is in the valid range.
    !
    implicit none

    ! Arguments:
    integer, intent(in) :: bitNumber

    ! Locals:
    logical                      :: isValid

    isValid = bitNumber >= minBitValue .and. bitNumber <= maxBitValue

    if (.not. isValid) then
      write(*,*) 'Supplied bit number is: ', bitNumber
      call rti_abort('bitNumberIsValidScalar (flg): This value is not valid. Ensure using flag variables defined in obsFlags_mod.')
    end if

  end subroutine checkBitNumberIsValidScalar

  !--------------------------------------------------------------------------
  ! bitNumberIsValidArray
  !--------------------------------------------------------------------------
  subroutine checkBitNumberIsValidArray(bitNumbers)
    !
    ! :Purpose: Check if a bit number is in the valid range.
    !
    implicit none

    ! Arguments:
    integer, intent(in) :: bitNumbers(:)

    ! Locals:
    logical                      :: isValid

    isValid = all(bitNumbers(:) >= minBitValue .and. bitNumbers(:) <= maxBitValue)

    if (.not. isValid) then
      write(*,*) 'Supplied bit numbers are: ', bitNumbers(:)
      call rti_abort('bitNumberIsValidArray (flg): This value is not valid. Ensure using flag variables defined in obsFlags_mod.')
    end if

  end subroutine checkBitNumberIsValidArray

  !--------------------------------------------------------------------------
  ! flg_flagIsOnFromRefValue
  !--------------------------------------------------------------------------
  function flg_flagIsOnFromRefValue(obsSpaceData, bodyIndex,  &
                                    refValue) result(flagIsOn)
    !
    ! :Purpose: Check if a specific flag bit is on.
    !
    implicit none

    ! Arguments:
    integer,          intent(in) :: bodyIndex
    type(struct_obs), intent(in) :: obsSpaceData
    integer,          intent(in) :: refValue
    ! Result:
    logical                      :: flagIsOn

    ! Locals:
    integer :: bitNumber, flagInteger

    bitNumber = flg_refValueToBitNum(refValue)
    flagInteger = obs_bodyElem_i(obsSpaceData, OBS_FLG, bodyIndex)
    flagIsOn = btest(flagInteger, bitNumber)

  end function flg_flagIsOnFromRefValue

  !--------------------------------------------------------------------------
  ! flg_flagIsOnFromObsData
  !--------------------------------------------------------------------------
  function flg_flagIsOnFromObsData(obsSpaceData, bodyIndex,  &
                                   bitNumberIn) result(flagIsOn)
    !
    ! :Purpose: Check if a specific flag bit is on.
    !
    implicit none

    ! Arguments:
    integer,          intent(in) :: bodyIndex
    type(struct_obs), intent(in) :: obsSpaceData
    integer,          intent(in) :: bitNumberIn
    ! Result:
    logical                      :: flagIsOn

    ! Locals:
    integer :: flagInteger, bitNumber

    bitNumber = bitNumberIn - flg_offset
    call checkBitNumberIsValid(bitNumber)

    flagInteger = obs_bodyElem_i(obsSpaceData, OBS_FLG, bodyIndex)
    flagIsOn = btest(flagInteger, bitNumber)

  end function flg_flagIsOnFromObsData

  !--------------------------------------------------------------------------
  ! flg_flagIsOnFromFlagInt
  !--------------------------------------------------------------------------
  function flg_flagIsOnFromFlagInt(flagInteger, bitNumberIn) result(flagIsOn)
    !
    ! :Purpose: Check if a specific flag bit is on.
    !
    implicit none

    ! Arguments:
    integer,          intent(in) :: flagInteger
    integer,          intent(in) :: bitNumberIn
    ! Result:
    logical                      :: flagIsOn

    ! Locals:
    integer :: bitNumber

    bitNumber = bitNumberIn - flg_offset
    call checkBitNumberIsValid(bitNumber)

    flagIsOn = btest(flagInteger, bitNumber)

  end function flg_flagIsOnFromFlagInt

  !--------------------------------------------------------------------------
  ! flg_flagsAreOnFromObsData
  !--------------------------------------------------------------------------
  function flg_flagsAreOnFromObsData(booleanOper, obsSpaceData, bodyIndex,  &
                                     bitNumbersIn) result(flagsAreOn)
    !
    ! :Purpose: Check if a specific flag bit is on.
    !
    implicit none

    ! Arguments:
    character(len=*), intent(in) :: booleanOper
    type(struct_obs), intent(in) :: obsSpaceData
    integer,          intent(in) :: bodyIndex
    integer,          intent(in) :: bitNumbersIn(:)
    ! Result:
    logical                      :: flagsAreOn

    ! Locals:
    integer :: flagInteger, numBitNumbers, bitIndex
    integer :: bitNumbers(size(bitNumbersIn))

    numBitNumbers = size(bitNumbers)

    bitNumbers(:) = bitNumbersIn(:) - flg_offset
    call checkBitNumberIsValid(bitNumbers)

    flagInteger = obs_bodyElem_i(obsSpaceData, OBS_FLG, bodyIndex)

    if (trim(booleanOper) == 'OR') then
      flagsAreOn = .false.
      do bitIndex = 1, numBitNumbers
        flagsAreOn = flagsAreOn .or. btest(flagInteger, bitNumbers(bitIndex))
      end do
    else
      write(*,*) 'booleanOper = ***', trim(booleanOper), '***'
      call rti_abort('flg_flagsAreOnFromObsData: Only OR is implemented so far')
    end if

  end function flg_flagsAreOnFromObsData

  !--------------------------------------------------------------------------
  ! flg_flagsAreOnFromFlagInt
  !--------------------------------------------------------------------------
  function flg_flagsAreOnFromFlagInt(booleanOper, flagInteger, &
                                     bitNumbersIn) result(flagsAreOn)
    !
    ! :Purpose: Check if a specific flag bit is on.
    !
    implicit none

    ! Arguments:
    character(len=*), intent(in) :: booleanOper
    integer,          intent(in) :: flagInteger
    integer,          intent(in) :: bitNumbersIn(:)
    ! Result:
    logical                      :: flagsAreOn

    ! Locals:
    integer :: numBitNumbers, bitIndex
    integer :: bitNumbers(size(bitNumbersIn))

    numBitNumbers = size(bitNumbers)

    bitNumbers(:) = bitNumbersIn(:) - flg_offset
    call checkBitNumberIsValid(bitNumbers)

    if (trim(booleanOper) == 'OR') then
      flagsAreOn = .false.
      do bitIndex = 1, numBitNumbers
        flagsAreOn = flagsAreOn .or. btest(flagInteger, bitNumbers(bitIndex))
      end do
    else
      write(*,*) 'booleanOper = ***', trim(booleanOper), '***'
      call rti_abort('flg_flagsAreOnFromFlagInt: Only OR is implemented so far')
    end if

  end function flg_flagsAreOnFromFlagInt

  !--------------------------------------------------------------------------
  ! flg_resetFlag
  !--------------------------------------------------------------------------
  subroutine flg_resetFlag(obsSpaceData, bodyIndex)
    !
    ! :Purpose: Reset the value of the flag integer to zero.
    !
    implicit none

    ! Arguments:
    integer,                    intent(in)    :: bodyIndex
    type(struct_obs),           intent(inout) :: obsSpaceData

    call obs_bodySet_i(obsSpaceData, OBS_FLG, bodyIndex, 0)
 
  end subroutine flg_resetFlag

  !--------------------------------------------------------------------------
  ! flg_setFlagFromObsData
  !--------------------------------------------------------------------------
  subroutine flg_setFlagFromObsData(obsSpaceData, bodyIndex,  &
                                    bitNumberIn)
    !
    ! :Purpose: Set the value of a specific flag bit.
    !
    implicit none

    ! Arguments:
    integer,          intent(in)    :: bodyIndex
    type(struct_obs), intent(inout) :: obsSpaceData
    integer,          intent(in)    :: bitNumberIn

    ! Locals:
    integer :: flagIntegerOrig, flagIntegerUpdated, bitNumber

    bitNumber = bitNumberIn - flg_offset
    call checkBitNumberIsValid(bitNumber)

    flagIntegerOrig = obs_bodyElem_i(obsSpaceData, OBS_FLG, bodyIndex)
    flagIntegerUpdated = ibset(flagIntegerOrig, bitNumber)
    call obs_bodySet_i(obsSpaceData, OBS_FLG, bodyIndex, flagIntegerUpdated)
 
  end subroutine flg_setFlagFromObsData

  !--------------------------------------------------------------------------
  ! flg_setFlagsFromObsData
  !--------------------------------------------------------------------------
  subroutine flg_setFlagsFromObsData(obsSpaceData, bodyIndex, bitNumbersIn)
    !
    ! :Purpose: Set the value of multiple specified flag bits.
    !
    implicit none

    ! Arguments:
    integer,                    intent(in)    :: bodyIndex
    type(struct_obs),           intent(inout) :: obsSpaceData
    integer,                    intent(in)    :: bitNumbersIn(:)

    ! Locals:
    integer :: flagIntegerOrig, flagIntegerUpdated
    integer :: numBitsToSet, bitIndex
    integer :: bitNumbers(size(bitNumbersIn))

    numBitsToSet = size(bitNumbers)

    bitNumbers(:) = bitNumbersIn(:) - flg_offset
    call checkBitNumberIsValid(bitNumbers)

    do bitIndex = 1, numBitsToSet
      flagIntegerOrig = obs_bodyElem_i(obsSpaceData, OBS_FLG, bodyIndex)
      flagIntegerUpdated = ibset(flagIntegerOrig, bitNumbers(bitIndex))
      call obs_bodySet_i(obsSpaceData, OBS_FLG, bodyIndex, flagIntegerUpdated)
    end do
 
  end subroutine flg_setFlagsFromObsData

  !--------------------------------------------------------------------------
  ! flg_setFlagFromFlagInt
  !--------------------------------------------------------------------------
  subroutine flg_setFlagFromFlagInt(flagInteger, bitNumberIn)
    !
    ! :Purpose: Set the value of a specific flag bit.
    !
    implicit none

    ! Arguments:
    integer,          intent(inout) :: flagInteger
    integer,          intent(in)    :: bitNumberIn

    ! Locals:
    integer :: bitNumber

    bitNumber = bitNumberIn - flg_offset
    call checkBitNumberIsValid(bitNumber)

    flagInteger = ibset(flagInteger, bitNumber)
 
  end subroutine flg_setFlagFromFlagInt

  !--------------------------------------------------------------------------
  ! flg_setFlagsFromFlagInt
  !--------------------------------------------------------------------------
  subroutine flg_setFlagsFromFlagInt(flagInteger, bitNumbersIn)
    !
    ! :Purpose: Set the value of multiple specified flag bits.
    !
    implicit none

    ! Arguments:
    integer,                    intent(inout) :: flagInteger
    integer,                    intent(in)    :: bitNumbersIn(:)

    ! Locals:
    integer :: numBitsToSet, bitIndex
    integer :: bitNumbers(size(bitNumbersIn))

    numBitsToSet = size(bitNumbers)

    bitNumbers(:) = bitNumbersIn(:) - flg_offset
    call checkBitNumberIsValid(bitNumbers)

    do bitIndex = 1, numBitsToSet
      flagInteger = ibset(flagInteger, bitNumbers(bitIndex))
    end do
 
  end subroutine flg_setFlagsFromFlagInt

  !--------------------------------------------------------------------------
  ! flg_clearFlagFromObsData
  !--------------------------------------------------------------------------
  subroutine flg_clearFlagFromObsData(obsSpaceData, bodyIndex,  &
                                      bitNumberIn)
    !
    ! :Purpose: Clear the value of a specific flag bit.
    !
    implicit none

    ! Arguments:
    integer,          intent(in)    :: bodyIndex
    type(struct_obs), intent(inout) :: obsSpaceData
    integer,          intent(in)    :: bitNumberIn

    ! Locals:
    integer :: flagIntegerOrig, flagIntegerUpdated, bitNumber

    bitNumber = bitNumberIn - flg_offset
    call checkBitNumberIsValid(bitNumber)

    flagIntegerOrig = obs_bodyElem_i(obsSpaceData, OBS_FLG, bodyIndex)
    flagIntegerUpdated = ibclr(flagIntegerOrig, bitNumber)
    call obs_bodySet_i(obsSpaceData, OBS_FLG, bodyIndex, flagIntegerUpdated)
 
  end subroutine flg_clearFlagFromObsData

  !--------------------------------------------------------------------------
  ! flg_clearFlagFromFlagInt
  !--------------------------------------------------------------------------
  subroutine flg_clearFlagFromFlagInt(flagInteger, bitNumberIn)
    !
    ! :Purpose: Clear the value of a specific flag bit.
    !
    implicit none

    ! Arguments:
    integer,          intent(inout) :: flagInteger
    integer,          intent(in)    :: bitNumberIn

    ! Locals
    integer :: bitNumber

    bitNumber = bitNumberIn - flg_offset
    call checkBitNumberIsValid(bitNumber)

    flagInteger = ibclr(flagInteger, bitNumber)
 
  end subroutine flg_clearFlagFromFlagInt

  !--------------------------------------------------------------------------
  ! flg_refValueTobitNum
  !--------------------------------------------------------------------------
  function flg_refValueTobitNum(refValue) result(bitNumber)
    !
    ! :Purpose: Convert bit numbers to reference values using the magic formula.
    !
    implicit none

    ! Arguments:
    integer, intent(in) :: refValue
    ! Result:
    integer             :: bitNumber

    bitNumber = 13 - refValue

  end function flg_refValueTobitNum

end module obsFlags_mod
