SRC_FILES=""
SRC_FILES="$SRC_FILES codeprecision_mod.ftn90 "
SRC_FILES="$SRC_FILES clib_interfaces_mod.ftn90 earthconstants_mod.f90 mathphysconstants_mod.f90 "
SRC_FILES="$SRC_FILES obsspacedata_mod.f90 utilities_mod.f90"
SRC_FILES="$SRC_FILES bgckmicrowave_mod.f90 mpi_mod.f90"
