SRC_FILES=""
SRC_FILES="$SRC_FILES utilities_mod.f90"
SRC_FILES="$SRC_FILES mpi_mod.f90"
SRC_FILES="$SRC_FILES bufr_mod.f90 clib_interfaces_mod.ftn90 mathphysconstants_mod.f90 mpivar_mod.f90"
SRC_FILES="$SRC_FILES earthconstants_mod.f90 horizontalcoord_mod.f90 ramdisk_mod.f90 timecoord_mod.f90 varnamelist_mod.f90 verticalcoord_mod.f90"
SRC_FILES="$SRC_FILES analysisgrid_mod.f90 filenames_mod.f90 gridstatevector_mod.f90"
SRC_FILES="$SRC_FILES ensemblestatevector_mod.f90"
