SRC_FILES=""
SRC_FILES="$SRC_FILES codeprecision_mod.ftn90 utilities_mod.f90"
SRC_FILES="$SRC_FILES earthconstants_mod.f90 mathphysconstants_mod.f90 mpi_mod.f90 "
SRC_FILES="$SRC_FILES bufr_mod.f90 clib_interfaces_mod.ftn90 codtyp_mod.f90 obsspacedata_mod.f90"
SRC_FILES="$SRC_FILES mpivar_mod.f90 obsUtil_mod.f90 ramdisk_mod.f90"
SRC_FILES="$SRC_FILES burpread_mod.f90 obssubspacedata_mod.f90 sqlite_read_mod.f90"
SRC_FILES="$SRC_FILES burpfiles_mod.f90 cmafiles_mod.f90 sqlitefiles_mod.f90"
SRC_FILES="$SRC_FILES obsfiles_mod.f90"
