SRC_FILES=""
SRC_FILES="$SRC_FILES utilities_mod.f90"
SRC_FILES="$SRC_FILES mpi_mod.f90"
SRC_FILES="$SRC_FILES bufr_mod.f90 clib_interfaces_mod.ftn90 codeprecision_mod.ftn90 earthconstants_mod.f90 mathphysconstants_mod.f90 mpivar_mod.f90 "
SRC_FILES="$SRC_FILES horizontalcoord_mod.f90 physicsfunctions_mod.f90 ramdisk_mod.f90 timecoord_mod.f90 varnamelist_mod.f90 verticalcoord_mod.f90"
SRC_FILES="$SRC_FILES codtyp_mod.f90 gridstatevector_mod.f90 obsspacedata_mod.f90"
<<<<<<< HEAD
SRC_FILES="$SRC_FILES analysisgrid_mod.f90 filenames_mod.f90 humiditylimits_mod.f90 obsUtil_mod.f90 presprofileoperators_mod.f90 rttov_interfaces_mod.ftn90"
SRC_FILES="$SRC_FILES burpread_mod.f90 columndata_mod.f90 ensemblestatevector_mod.f90 globalspectraltransform_mod.f90 lamspectraltransform_mod.f90 obssubspacedata_mod.f90 ozoneclim_mod.f90 rmatrix_mod.f90 sqlite_read_mod.f90 tovs_extrap_mod.f90 tt2phi_mod.f90"
SRC_FILES="$SRC_FILES burpfiles_mod.f90 cmafiles_mod.f90 obstimeinterp_mod.f90 slantprofilelatlon_mod.f90 sqlitefiles_mod.f90 tovs_nl_mod.f90 variabletransforms_mod.f90 windrotation_mod.f90"
SRC_FILES="$SRC_FILES obsfiles_mod.f90 statetocolumn_mod.f90"
SRC_FILES="$SRC_FILES chem_setup_mod.f90 gps_mod.f90"
=======
SRC_FILES="$SRC_FILES analysisgrid_mod.f90 filenames_mod.f90 humiditylimits_mod.f90 obsUtil_mod.f90"
SRC_FILES="$SRC_FILES burpread_mod.f90 ensemblestatevector_mod.f90 globalspectraltransform_mod.f90 lamspectraltransform_mod.f90 obssubspacedata_mod.f90 obsVariableTransforms_mod.f90 sqlite_read_mod.f90 tt2phi_mod.f90"
SRC_FILES="$SRC_FILES burpfiles_mod.f90 cmafiles_mod.f90 columndata_mod.f90 gridVariableTransforms_mod.f90 obstimeinterp_mod.f90 presprofileoperators_mod.f90 rttov_interfaces_mod.ftn90 sqlitefiles_mod.f90 windrotation_mod.f90"
SRC_FILES="$SRC_FILES obsfiles_mod.f90 ozoneclim_mod.f90 rmatrix_mod.f90 statetocolumn_mod.f90 tovs_extrap_mod.f90"
SRC_FILES="$SRC_FILES chem_setup_mod.f90 gps_mod.f90 tovs_nl_mod.f90"
>>>>>>> Issue #247: Reshuffling of the code in preparation for further changes
SRC_FILES="$SRC_FILES bmatrixchem_mod.f90 obsfilter_mod.f90"
SRC_FILES="$SRC_FILES chem_obserrors_mod.f90 chem_obsoperators_mod.f90 tovs_lin_mod.f90"
SRC_FILES="$SRC_FILES multi_ir_bgck_mod.f90 obserrors_mod.f90 obsoperators_mod.f90 randomnumber_mod.f90"
SRC_FILES="$SRC_FILES innovation_mod.f90 thinning_mod.f90"
