SRC_FILES=""
SRC_FILES="$SRC_FILES utilities_mod.f90"
SRC_FILES="$SRC_FILES mpi_mod.f90"
SRC_FILES="$SRC_FILES bufr_mod.f90 earthconstants_mod.f90 mathphysconstants_mod.f90 mpivar_mod.f90"
SRC_FILES="$SRC_FILES horizontalcoord_mod.f90 localizationfunction_mod.f90 timecoord_mod.f90 varnamelist_mod.f90 verticalcoord_mod.f90"
SRC_FILES="$SRC_FILES analysisgrid_mod.f90 globalspectraltransform_mod.f90 gridstatevector_mod.f90 lamspectraltransform_mod.f90 menetrierdiag_mod.f90 spectralfilter_mod.f90"
SRC_FILES="$SRC_FILES calcstatsglb_mod.f90 calcstatslam_mod.f90"
