#!/bin/ksh

set -e

SEQ_MAESTRO_SHORTCUT=${SEQ_MAESTRO_SHORTCUT:-". ssmuse-sh -d eccc/cmo/isst/maestro/1.5.3.3"}
which nodelister 1>/dev/null 2>&1 || ${SEQ_MAESTRO_SHORTCUT}
which cmcarc

export SEQ_EXP_HOME=$(dirname $(true_path ${0}))
unittests=${*}

## Si 'overwrite_listings=yes' alors on va effacer les listings precedents
if [ -n "${COLLECT_UNITTEST_LISTINGS_OVERWRITE_LISTINGS}" ]; then
    overwrite_listings=${COLLECT_UNITTEST_LISTINGS_OVERWRITE_LISTINGS}
else
    overwrite_listings=no
fi

LOCAL_GITDIR=$(cd ${SEQ_EXP_HOME}; git rev-parse --git-dir)
gittag=${gittag:-$(git --git-dir=${LOCAL_GITDIR} describe)}

tasks=${COLLECT_UNITTEST_LISTINGS_TASKS:-"get run download check"}

if [ -n "${COLLECT_UNITTEST_LISTINGS_EXPDATE}" ]; then
    ExpDate=${COLLECT_UNITTEST_LISTINGS_EXPDATE}
else
    ExpDate=$(basename $(/bin/ls -t1 ${SEQ_EXP_HOME}/logs/*_nodelog | head -1) _nodelog)
fi

echo "Using ExpDate=${ExpDate}"

if [[ -z "${unittests}" ]]; then
    unittests=$(cd ${SEQ_EXP_HOME}/resources/Tests; find . -name UnitTest | xargs -L1 dirname | cut -c3-)
fi

if [ -n "${collect_unittest_listings_workdir}" ]; then
    if [ ! -d "${collect_unittest_listings_workdir}" ]; then
        mkdir -p ${collect_unittest_listings_workdir}
    fi
    cd ${collect_unittest_listings_workdir}
else
    cd ${TMPDIR}
fi

function result_dir {
    set -e
    __result_dir_unittest__=$1

    __result_dir_config__=${SEQ_EXP_HOME}/config/Tests/${__result_dir_unittest__}.cfg
    if [[ ! -f "${__result_dir_config__}" ]]; then
	echo "Le fichier '${__result_dir_config__}' n'existe pas (ce doit etre le path complet vers un fichier de configuration)"
	return
    fi
    unset UnitTest_reference
    eval $(grep UnitTest_reference ${__result_dir_config__})
    if [ -z "${UnitTest_reference}" ]; then
	echo "La variable 'UnitTest_reference' n'a pas ete initialisee dans le fichier ${__result_dir_config__}"
	return
    fi
    if [ -n "${collect_unittest_listings_output}" ]; then
        echo ${collect_unittest_listings_output}/${__result_dir_unittest__}
    else
        echo ${UnitTest_reference##*:}
    fi

    unset __result_dir_unittest__ __result_dir_config__ UnitTest_reference
}

for unittest in ${unittests}; do
    echo "travail avec '${unittest}' (tag ${gittag}) dans le repertoire $PWD"
    for task in ${tasks}; do
	nodename=/Tests/${unittest}/UnitTest/${task}
	filename=$(echo ${nodename} | cut -c2- | sed 's!/!\.!g')
	nodelister -n ${nodename} -d ${ExpDate} > ${filename} || true
	cmcarc -f listings_${gittag}.ca -a ${filename}
	rm ${filename}
    done

    result=$(result_dir ${unittest})/listings_${gittag}.ca
    if [ -z "${result}" ]; then
        continue
    elif [ -f "${result}" ]; then
	if [ "${overwrite_listings}" != 'yes' ]; then
	    echo "Le fichier '${result}' existe deja.  On ne l'efface pas"
	    cmcarc -f ${result} -t -v
	    continue
	else
            chmod u+w ${result}
	    rm -v ${result}
	fi
    elif [ ! -d "${result%/*}" ]; then
        mkdir -p ${result%/*}
    fi

    mv listings_${gittag}.ca ${result}
    cmcarc -f ${result} -t -v
    chmod -wx ${result}
done
