#! /bin/sh
export MIDAS_COMPILE_ADD_DEBUG_OPTIONS=${MIDAS_COMPILE_ADD_DEBUG_OPTIONS:-${COMPILE_MIDAS_ADD_DEBUG_OPTIONS}}
export MIDAS_COMPILE_DIR_MAIN=${MIDAS_COMPILE_DIR_MAIN:-${COMPILEDIR_MIDAS_MAIN}}
export MIDAS_COMPILE_DIR_ID=${MIDAS_COMPILE_DIR_ID:-${COMPILEDIR_MIDAS_ID}}
