#! /bin/sh

###############################################################################
##  MIDAS automated build script
##
##  @SYNOPSIS
##      * specify your configuration by exporting some MIDAS_ variables in the environment
##        (consult `./config.dot.sh` for these variables)
##
##      * compile, link and install all programs
##        ```
##        ./midas_build
##        ```
##      * use '-d', '-debug' or '--debug' to activate debug options, which is equivalent to setting 'MIDAS_COMPILE_ADD_DEBUG_OPTIONS=yes'
##      * use '-opt-report' to activate compiler optimization report, which is equivalent to setting 'MIDAS_COMPILE_OPTIMIZE_REPORT=yes'
##      * use '--codecov ${datapath}' to activate code coverage, which is equivalent to setting 'MIDAS_COMPILE_CODECOVERAGE_DATAPATH=${datapath}'
##
##         (see other options below or with './midas_build --help')
##
##  @REFERENCES
##      * `./README.md`
##
##  @AUTHORS
##      Martin Deshaies-Jacques (@mad001) - CMDA - January 2020
##
##  @MAJOR MODIFICATIONS
##      * november 2024 - adapatation and simplification for the usage of cmake
##
###############################################################################

##=========================================================
## some prior defitions
typeset __target
typeset __job
typeset __job_opt
typeset __here
typeset __abs_all

__here=$(pwd)
__date=$(date +%Y%m%d%H%M%S)
__dateLong=$(date)
__dateStampBeg=$(date +%s)
__toplevel=$(git rev-parse --show-toplevel)
__revstring=$(${__toplevel}/midas.version)

##=========================================================
##  checking if the environment has already been defined
if [ "${MIDAS_CONFIG_ALREADY_SOURCED}" == "true" ]; then
    echo "+-----------------------------------------+"
    echo "|                                         |"
    echo "| WARNING: config.dot.sh already sourced! |"
    echo "|     possible environment conflict       |"
    echo "|   open a new shell before proceeding    |"
    echo "|                                         |"
    echo "+-----------------------------------------+"
    exit 1
fi

##=========================================================
##  sourcing user configuration
if [ "${ORDENV_PLAT}" != rhel-8-icelake-64 -a "${ORDENV_PLAT}" != rhel-9-graniterapids-64 ];then
    echo "Only ORDENV_PLAT=rhel-8-icelake-64 or ORDENV_PLAT=rhel-9-graniterapids-64 are supported"
    exit 1
fi

##=========================================================
##  finding all possible targets
__abs_all=$(cd ${__toplevel}/src; ls programs/*.f90 | sed 's/programs\/\(.*\).f90/\1/')
__abs_external='splitobs monitor'
__abs_all="${__abs_all} ${__abs_external}"

##=========================================================
##  parsing input and building job for submissions
##

__abs_exist_list=${__abs_all}

__fresh_build_directory=--fresh
## When using 'midas_build', we want verbose compilation listing
## This can be overriden with '--no-verbose' option
MIDAS_COMPILE_VERBOSE=TRUE

function print_usage {
    set -euo pipefail

    echo "midas_build: "
    echo "        -d|-debug|--debug: compile using the debug options (override the variable 'MIDAS_COMPILE_ADD_DEBUG_OPTIONS')"
    echo "        --opt-report: add the compiler options to output the optimization report (override the variable 'MIDAS_COMPILE_OPTIMIZE_REPORT')"
    echo "        --vtune: activate the compiler options to allow 'vtune' to profile the code"
    echo "        --codecov: activate the code covering compiler options (needs a directory for storing the code coverage information) (override the variable 'MIDAS_COMPILE_CODECOVERAGE_DATAPATH')"
    echo "        --local: avoid launching a batch job to compile (override the variable 'MIDAS_COMPILE_'HEADNODE_FRONTEND)"
    echo "        --no-fresh: won't erase the build directory if it already exists before compilation"
    echo "        --no-clean: do not erase the build directory after the compilation (override the variable 'MIDAS_COMPILE_CLEAN'"
    echo "        --keep-listing: do not erase compilation listing after the compilation (override the variable 'MIDAS_COMPILE_KEEP_LISTING')"
    echo "        --append-version-id-builddir: append version id to the build directory (override the variable 'MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR'"
    echo "        --no-verbose: Turn off the verbose output for the compilation (override the variable 'MIDAS_COMPILE_VERBOSE')"
    echo "        -h|-help|--help: show this help"
} ## End of 'function print_usage'

if [ $# -gt 0 ]; then
    while [[ $# > 0 ]]; do
        arg=${1}

        if [[ "${arg}" = -d || "${arg}" = -debug || "${arg}" = --debug ]]; then
            export MIDAS_COMPILE_ADD_DEBUG_OPTIONS=yes
        elif [[ "${arg}" = --opt-report ]]; then
            export MIDAS_COMPILE_OPTIMIZE_REPORT=yes
        elif [[ "${arg}" = --optreport ]]; then
            echo "midas_build: use '--opt-report' instead of '--optreport'" >&2
            exit 1
        elif [[ "${arg}" = --vtune ]]; then
            __vtune_options="-debug -parallel-source-info=2"
            export MIDAS_COMPILE_COMPF_GLOBAL="${MIDAS_COMPILE_COMPF_GLOBAL} ${__vtune_options}"
            echo "midas_build: Adding compilation options '${__vtune_options}' needed for 'vtune'"
            unset __vtune_options
        elif [[ "${arg}" = --codecov ]]; then
            if [[ $# -lt 2 ]]; then
                echo "midas_build: The option '--codecov' must be followed by a path where to put the code coverage files" >&2
                exit 1
            elif [[ ${2} = -* || -z "${2}" ]]; then
                echo "midas_build: The option '--codecov' must be followed by a path where to put the code coverage files" >&2
                exit 1
            fi
            export MIDAS_COMPILE_CODECOVERAGE_DATAPATH=${2}
            shift
        elif [[ "${arg}" = --local ]]; then
            MIDAS_COMPILE_HEADNODE_FRONTEND=true
        elif [[ "${arg}" = --no-verbose ]]; then
            MIDAS_COMPILE_VERBOSE=FALSE  ## We use 'FALSE' here because it is the standard for the variable 'CMAKE_VERBOSE_MAKEFILE'
        elif [[ "${arg}" = --no-fresh ]]; then
            __fresh_build_directory=--no-fresh
        elif [[ "${arg}" = --no-clean ]]; then
            MIDAS_COMPILE_CLEAN=false
        elif [[ "${arg}" = --keep-listing ]]; then
            MIDAS_COMPILE_KEEP_LISTING=true
        elif [[ "${arg}" = --append-version-id-builddir ]]; then
            if [[  -n "${MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR}" ]]; then
                echo "override 'MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR' from '${MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR}' to 'true'"
            fi
            export MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR=true
        elif [[ "${arg}" = -h || "${arg}" = -help || "${arg}" = --help ]]; then
            print_usage
            exit 1
        elif [[ "${arg}" = -* ]]; then
            echo "midas_build: this option '${arg}' is not allowed" >&2
            if [[ "${arg}" = --code-cov ]]; then
                echo "midas_build: are you meaning '--codecov'?" >&2
            fi
            echo
            print_usage
            exit 1
        elif [[ "${arg}" = all ]]; then
            __target=${arg}
        elif [[ -n "${__target}" ]]; then
            if [[ "${arg}" = *.Abs ]]; then
                __new_target=$(basename ${arg} .Abs)
                echo "midas_build: changing target ${arg} to ${__new_target}"
                __target="${__target} ${__new_target}"
            else
                __target="${__target} ${arg}"
            fi
        else
            if [[ "${arg}" = *.Abs ]]; then
                __new_target=$(basename ${arg} .Abs)
                echo "midas_build: changing target ${__target} to ${__new_target}"
                __target=${__new_target}
            else
                __target=${arg}
            fi
        fi

        shift
    done ## End of 'while [[ $# > 0 ]]'

    if [[ -n "${__target}" && "${__target}" != all ]]; then
        __abs_exist_list=
        for __targ in ${__target}; do
            grep_status=0
            echo ${__abs_all} | grep -sq "\b${__targ}\b" || grep_status=1
            if [[ "${grep_status}" -eq 0 ]]; then
                if [[  -n "${__abs_exist_list}" ]]; then
                    __abs_exist_list="${__abs_exist_list} ${__targ}"
                else
                    __abs_exist_list=${__targ}
                fi
            fi
        done
    fi
fi ## End of 'else' associated to 'if [ $# -gt 0 ]'

## default: make all
if [[ -z "${__target}" ]]; then
  __target=all
fi

__midas_dot_cfg=${__here}/config.dot.sh
echo "Sourcing MIDAS build configuration <<< ${__midas_dot_cfg}"
__midas_source_config_status__=0
source ${__midas_dot_cfg} --cmake --no-show-instructions ${__fresh_build_directory} &> ${__here}/.tmp.config.out || __midas_source_config_status__=1

__listing_config=${__here}/${MIDAS_COMPILE_JOBNAME}.config-${__date}.out
__listing_frontend=${__here}/${MIDAS_COMPILE_JOBNAME}.${MIDAS_COMPILE_FRONTEND}-${__date}.out
if [ "${__midas_source_config_status__}" -ne 0 ]; then
    mv ${__here}/.tmp.config.out ${__listing_config}
    echo "An error occured in the build configuration, consult ${__listing_config}"
    exit 1
fi

mv ${__here}/.tmp.config.out ${__listing_config}

cd ${__here}

function are_jobs_completed {
    set -e
    typeset job_or_pid_front=$1
    typeset headnode_frontend=$2

    typeset __sleep_interval=3
    typeset __front_done=0
    while true; do
        typeset __status=0

        if [ "${__front_done}" = 0 ]; then
            if [ "${headnode_frontend}" = true ]; then
                [ $(ps ${job_or_pid_front} | wc -l) -le 1 ] && __status=1
                __id_type="pid"
            else
                echo qstat ${job_or_pid_front} | ssh ${MIDAS_COMPILE_FRONTEND} bash --login 1>/dev/null 2>&1 || __status=$?
                __id_type="jobid"
            fi
            if [ "${__status}" -ne 0 ]; then
                echo "Compilation on ${MIDAS_COMPILE_FRONTEND} \
(${__id_type}: ${job_or_pid_front}) has finished."
                __front_done=1
        fi; fi

        [ "${__front_done}" = 1 ] && break
        sleep ${__sleep_interval}
    done
}

function abs_prefix {
    typeset abs_name=${1}
    typeset revstring=${2:-}
    typeset platform=_${3:-${ORDENV_PLAT}}

    if ${__toplevel}/tools/midas_scripts/midas.isFileInList "${__abs}" in "${__abs_external}"; then
        typeset __abs_prfx=tools/midas.
        if [ "${abs_name}" = monitor ]; then
            platform=
        fi
    else
        typeset __abs_prfx=src/programs/midas-
    fi

    echo ${__abs_prfx}${abs_name}${platform}${revstring}.Abs
}

function printHeader {
    echo
    echo "+---| MIDAS BUILDER starts |--------------------------------------------------"
    echo "| ${__dateLong} (${__date})"
    echo "| targets"
    for __t in ${__target}; do
        echo "| * ${__t}"
    done
    echo "| code version : ${__revstring}"
    echo "| debug : ${MIDAS_COMPILE_ADD_DEBUG_OPTIONS}"
    echo "| codecoverage : ${MIDAS_COMPILE_CODECOVERAGE_DATAPATH:-no}"
    echo "| optimization report : ${MIDAS_COMPILE_OPTIMIZE_REPORT}"
    echo "| build directory : ${MIDAS_COMPILE_DIR_BUILD}"
    if [ -n "${__abs_exist_list}" ]; then
        ##-- an absolute is in the targets; installation will be attempted
        ##   only then the build dir can be removed
        if [ "${MIDAS_COMPILE_CLEAN}" = true ]; then
            echo "|   (will be removed if installation is successful (use '--no-clean' to avoid that))"
        fi
        echo "| installation directory : ${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR}"
    else
        echo "| no installation (no absolute target)"
    fi
    if [ "${MIDAS_COMPILE_HEADNODE_FRONTEND}" = true ]; then
        echo "| compiling locally"
    fi
    echo "| listings"
    echo "| * ${__listing_frontend}"
    if [ "${MIDAS_COMPILE_KEEP_LISTING}" = false ]; then
        echo "|   (will be removed if compilation is successful (use '--keep-listing' to avoid that))"
    fi
    echo "+-----------------------------------------------------------------------------"
    echo
}

function printFooter {
    __dateStampEnd=$(date +%s)
    __dateDiff=$((${__dateStampEnd}-${__dateStampBeg}))
    echo
    echo "+---| MIDAS BUILDER ends |----------------------------------------------------"
    echo "| $(date)"
    echo "| execution time : ${__dateDiff} s"
    echo "+-----------------------------------------------------------------------------"
    echo
}

##=========================================================
## Header
printHeader

cd ${MIDAS_COMPILE_DIR_BUILD}

##=========================================================
##  Checking presence of absolute targets in 'src/programs/CMakeLists.txt'
##  Check prior existence of absolutes : remove them first
for __abs in ${__abs_exist_list}; do
    ## external programs are not expected in src/programs/CMakeLists.txt
    if ${__toplevel}/tools/midas_scripts/midas.isFileInList "${__abs}" not in "${__abs_external}"; then
        typeset __search=$(grep "add_executable(${__abs}" ${__toplevel}/src/programs/CMakeLists.txt)
        if [ -z "${__search}" ]; then
            echo "<!> ${__abs} target not in src/programs/CMakeLists.txt"
            exit 1
        fi
    fi
done
echo "Checking prior existence of target absolutes"
for __abs in ${__abs_exist_list}; do
    typeset __abs_full=${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR}/$(basename $(abs_prefix ${__abs} -${__revstring}))
    if [ -f "${__abs_full}" ]; then
        echo "   > ${__abs_full} exists; removing it" | tee -a ${__listing_config}
        rm ${__abs_full}
    fi
done
echo

##=========================================================
##  Compilation job for submission
##-- passing active environment to the job
##  (before sourcing config.dot.sh)
cat > .compile_job << EOF
#! /bin/bash
set -ex

export MIDAS_COMPILE_FRONTEND=${MIDAS_COMPILE_FRONTEND}
export MIDAS_COMPILE_JOBNAME=${MIDAS_COMPILE_JOBNAME}
export MIDAS_COMPILE_DIR_MAIN=${MIDAS_COMPILE_DIR_MAIN}
export MIDAS_COMPILE_NCORES=${MIDAS_COMPILE_NCORES}
export MIDAS_ABS_LEAFDIR=${MIDAS_ABS_LEAFDIR}
export MIDAS_COMPILE_CLEAN=${MIDAS_COMPILE_CLEAN}
export MIDAS_COMPILE_HEADNODE_FRONTEND=${MIDAS_COMPILE_HEADNODE_FRONTEND}
export MIDAS_COMPILE_KEEP_LISTING=${MIDAS_COMPILE_KEEP_LISTING}
export MIDAS_COMPILE_ADD_DEBUG_OPTIONS=${MIDAS_COMPILE_ADD_DEBUG_OPTIONS}
export MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR=${MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR}
export MIDAS_COMPILE_OPTIMIZE_REPORT=${MIDAS_COMPILE_OPTIMIZE_REPORT}
[ -n "${MIDAS_COMPILE_CODECOVERAGE_DATAPATH}" ] && export MIDAS_COMPILE_CODECOVERAGE_DATAPATH=${MIDAS_COMPILE_CODECOVERAGE_DATAPATH}

cd ${__here}

## No need to rerun 'cmake' here since it has already been run by the
## calling script
source ${__midas_dot_cfg} --no-cmake --no-show-instructions

make --jobs=${MIDAS_COMPILE_NCORES} ${__target}
EOF

##=========================================================
##  Compilation on frontend
echo "========================================================================"
echo "Job submitted:"
echo "\`\`\`"
cat .compile_job
echo "\`\`\`"
echo "========================================================================"
echo "... Launching compilation on ${MIDAS_COMPILE_FRONTEND}"
if [ "${MIDAS_COMPILE_HEADNODE_FRONTEND}" = true ]
then
    ## compile directly on head node
    echo "    > ${__listing_frontend}"
    make --jobs=${MIDAS_COMPILE_NCORES} ${__target} >  ${__listing_frontend} 2>&1 &
    __job_or_pid_frontend=$!
    echo "    ${MIDAS_COMPILE_FRONTEND} (headnode) compilation process id: ${__job_or_pid_frontend}"
else
    ## use ord_soumet
    __job_or_pid_frontend=$(ord_soumet .compile_job -jn ${MIDAS_COMPILE_JOBNAME} \
        -mach ${MIDAS_COMPILE_FRONTEND} -listing ${PWD} -w ${__ordsoumet_wallclock:-20} \
        -cpus ${MIDAS_COMPILE_NCORES}  -m 8G -shell /bin/bash)
fi

##=========================================================
## waiting for compilation to terminate
echo
echo "Compilation underway: ${__job_or_pid_frontend}"
echo "Build directory: ${MIDAS_COMPILE_DIR_BUILD}"
echo

are_jobs_completed ${__job_or_pid_frontend} ${MIDAS_COMPILE_HEADNODE_FRONTEND}
rm .compile_job

##-- renaming ord_soumet frontend listing
if [ ! -f "${__listing_frontend}" ]; then
    __listing_frontend_search="^${MIDAS_COMPILE_JOBNAME}.${MIDAS_COMPILE_FRONTEND}-.*-$(date +%Y%m%d).*\.out$"
    __listing_frontend_found=$(ls -rt1 ${MIDAS_COMPILE_JOBNAME}* | grep "${__listing_frontend_search}" | tail -n 1)
    mv ${__listing_frontend_found}   ${__listing_frontend}
    mv ${__listing_frontend_found}.o ${__listing_frontend}.o
    unset __listing_frontend_search
    unset __listing_frontend_found
fi

##====| POST make processing |==================================================

## Organizing logs
cat ${__listing_frontend} >> ${__listing_config}
mv ${__listing_config} ${__listing_frontend}

##=========================================================
## Checking if compilation and linking have been successful

typeset __remarks=0
## Check for unused variables
typeset __remark_unused_variables=$(grep 'remark #7712: ' ${__listing_frontend} | sort -u)
if [ -n "${__remark_unused_variables}" ]; then
    echo
    echo "<!> Some unused variables have been found.  Would you please remove them?"
    echo
    echo "${__remark_unused_variables}"
    __remarks=1
fi

typeset __warnings=0
## Check for unused variables
typeset __warnings_all=$(grep -v '^icc: warning #10237: -lcilkrts linked in dynamically, static library not available$' ${__listing_frontend} | grep -A 2 'warning #')
if [ -n "${__warnings_all}" ]; then
    echo
    echo "<!> Some compiling warnings have been triggered."
    echo
    echo "${__warnings_all}"
    __warnings=1
fi

if [ -z "${__remark_unused_variables}" -a -z "${__warnings_all}" ]; then
    echo
    echo "No compilation warnings has been detected!"
fi

## regex elements to find errors
typeset __err_regex='error #|(?<!-)undefined|make.*Circular|[Ff]ailed| Error '

typeset __err_comp=0
typeset __err_front=$(grep -Pn "${__err_regex}" ${__listing_frontend})
if [ -n "${__err_front}" ]; then
    echo
    echo "<!> some error found in ${__listing_frontend}"
    echo "${__err_front}"
    __err_comp=1
    exit 1
fi

typeset __make_stop=1
typeset __make_stop=$(grep -i "^make:.*stop" ${__listing_frontend})
if [ -n "${__make_stop}" ]; then
    echo
    echo "<!> some error found in ${__listing_frontend}"
    echo "${__make_stop}"
    __err_comp=1
    exit 1
fi

##========================================================

if [ -n "${__abs_exist_list}" ]; then
    [ ! -d ${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR} ] && mkdir ${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR}
    ##  Verification of compiled programs
    typeset __status=0
    for __abs in ${__abs_exist_list}; do
        typeset __abs_installed=${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR}/$(basename $(abs_prefix ${__abs} -${__revstring}))
        if [ ! -f  "${__abs_installed}" ]; then
            echo "  <!> ${__abs_installed} not found"
            __status=1
        else
            echo "  ${__abs_installed} installed" >> .checkAbs
        fi
    done
    [ -f ".checkAbs" ] && ( cat .checkAbs >> ${__listing_frontend} && rm .checkAbs )

    if [ "${__status}" -eq 0 ]; then
        echo
        echo "+------------------------------+"
        echo "|                              |"
        echo "| MIDAS INSTALLATION COMPLETED |"
        echo "|   ALL PROGRAMS INSTALLED     |"
        echo "|                              |"
        echo "+------------------------------+"
        echo
        echo "  > ${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR}"
        echo

        ## Copy 'midas-config' to '${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR}'
        cp midas-config ${MIDAS_COMPILE_DIR_MAIN}/${MIDAS_ABS_LEAFDIR}

        if [ "${MIDAS_COMPILE_OPTIMIZE_REPORT}" = yes ]; then
            cat <<EOF
You will find the optimization reports (*.optrpt files) in one of the build directories:
   ${MIDAS_COMPILE_DIR_BUILD}/src/modules/CMakeFiles/midas.dir
   ${MIDAS_COMPILE_DIR_BUILD}/src/programs/CMakeFiles/*.dir
EOF
            if [ "${MIDAS_COMPILE_CLEAN}" = true ]; then
                echo "Do not erase the build directory to keep access to optimization report files"
            fi
        elif [ "${MIDAS_COMPILE_CLEAN}" = true ]; then
            echo
            echo "MIDAS_COMPILE_CLEAN=true"
            echo "(in your environment, profile or config.dot.sh)"
            echo " ... cleaning build directory ${MIDAS_COMPILE_DIR_BUILD}"
            make VERBOSE= clean
            cd ${MIDAS_SOURCE_DIR}
            rm -rf ${MIDAS_COMPILE_DIR_BUILD}
        fi
    else
        echo
        echo "+--------------------------------------+"
        echo "|                                      |"
        echo "| SOME PROGRAMS COULD NOT BE INSTALLED |"
        echo "|                                      |"
        echo "+--------------------------------------+"
        echo
        exit 1
    fi
fi ## End of 'if [ -n "${__abs_exist_list}" ]'

##=========================================================
## Some final clean up if compilation (and possibly linking
## and installation) was successful

if [ "${MIDAS_COMPILE_KEEP_LISTING}" = false ]; then
    echo
    echo "MIDAS_COMPILE_KEEP_LISTING=false"
    echo "(in your environment, profile or config.dot.sh)"
    echo " ... removing listings"
    rm ${__listing_frontend}
    [ -f ${__listing_frontend}.o ] && rm ${__listing_frontend}.o
fi

printFooter
