#!/bin/bash

set -e

DOMAIN_BASE=${1:-${HOME}/data_maestro/ords/SSM/midas}
SSM_PACKAGES=${2:-${DOMAIN_BASE}/packages}

cd $(git rev-parse --show-toplevel)/src/programs
./compile_all_plat.sh
cd ../../tools/monitor
make install PGM=${PWD}/../../compiledir/midas_abs/midas.monitor_$(../../midas.version.sh).Abs
cd ../..

VERSION=$(./midas.version.sh | cut -c3-)
## to set variables 'MACHINE_PPP' and 'MACHINE_SUPER'
. maestro/suites/midas_system_tests/set_machine_list.dot
cd ssm
./build_packages --midas-abs ${PWD}/../compiledir/midas_abs --packages ${SSM_PACKAGES}/${VERSION} --frontend ${MACHINE_PPP} --backend ${MACHINE_SUPER}
cd ..

cd ssm
./publish --packages ${SSM_PACKAGES}/${VERSION} --post-install ${PWD}/post-install --workdir ${PWD}/publish-workdir-$$ --domainpath ${DOMAIN_BASE}/${VERSION}

echo "You can use the SSM domain published with:"
echo "   . ssmuse-sh -d ${DOMAIN_BASE}/${VERSION}"
