#!/bin/bash

## This script builds SSM package for external libraries MIDAS needs:
##     f90sqlite
##     udfsqlite
##     perftools

set -e

SECONDS=0

typeset -r scriptName=package_external_libs

function say {
    printf "${scriptName}: ${*}\n"
} ## End of 'function say'

function die {
    say $@ >&2
    exit 1
} ## End of 'function die'

getArg () {
    set -e
    if [ $# -le 1 ]; then
        die "The option '$1' expects an argument"
    fi
    if [[ "$2" == -* ]]; then
        die "The option '$1' expects an argument but have '$2'"
    fi
    echo $2
} ## End of function 'getArg'

args=
while [ $# -gt 0 ]; do
    if [ "${1}" = --libs ]; then
        libs=$(getArg $1 $2)
        shift
    elif [ "${1}" = --compiler ]; then
        compiler=$(getArg $1 $2)
        shift
    elif [ "${1}" = --ssmpkgdestination ]; then
        ssmpkgdestination=$(getArg $1 $2)
        shift
    elif [ "${1}" = --workdir ]; then
        workdir=$(getArg $1 $2)
        shift
    else
        args="${args} ${1}"
    fi
    shift
done

if [ -n "${args}" ]; then
    die "Those arguments '${args}' have not been digested by the option parser"
fi

if [ -z "${libs}" ]; then
    libs="udfsqlite f90sqlite perftools hdf5 netcdf-c netcdf-fortran"
    #libs="perftools hdf5 netcdf-c netcdf-fortran"
    #libs=hdf5
    #libs="hdf5 netcdf-c"
    #libs=netcdf-fortran
    #libs=perftools
    #libs="udfsqlite f90sqlite"
fi

for optionarg in libs compiler ssmpkgdestination workdir; do
    eval optionvalue="\${${optionarg}}"
    if [ -z "${optionvalue}" ]; then
        die "The option '--${optionarg}' should be specified and non-empty"
    fi
done

if [[ -d "${workdir}" ]]; then
    die "The workdir directory ${workdir} exists!"
fi
mkdir -p ${workdir}

if [[ ! -d "${ssmpkgdestination}" ]]; then
    say "Creating '${ssmpkgdestination}'"
    mkdir -p ${ssmpkgdestination}
fi

build_control_file() {
    set -e

    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}

    if [[ "${lib}" = hdf5 ]]; then
        typeset -r summary="HDF5 library"
        typeset -r maintainer="MIDAS maintainers"
        typeset -r description="HDF5 is a data model, library, and file format for storing and managing data. It supports an unlimited variety of datatypes, and is designed for flexible and efficient I/O and for high volume and complex data. HDF5 is portable and is extensible, allowing applications to evolve in their use of HDF5. The HDF5 Technology suite includes tools and applications for managing, manipulating, viewing, and analyzing data in the HDF5 format. Please see https://support.hdfgroup.org/HDF5/ for more info."
    elif [[ "${lib}" =~ ^netcdf-.* ]]; then
        typeset -r summary="NetCDF library"
        typeset -r maintainer="MIDAS maintainers"
        typeset -r description="NetCDF (network Common Data Form) is a set of interfaces for array-oriented data access and a freely distributed collection of data access libraries for C, Fortran, C++, Java, and other languages. The netCDF libraries support a machine-independent format for representing scientific data. Together, the interfaces, libraries, and format support the creation, access, and sharing of scientific data. The main Website is: http://www.unidata.ucar.edu/software/netcdf"
    elif [[ "${lib}" = perftools ]]; then
        typeset -r summary="MPI-aware timing library"
        typeset -r maintainer="Michel Beland <michel.beland@ssc-spc.gc.ca>"
        typeset -r description="Timing library inspired by the hpm timing package on IBM Power systems under AIX."
    elif [[ "${lib}" = udfsqlite ]]; then
        typeset -r summary="Supplementary SQL functions"
        typeset -r maintainer="Anthony Chartier <anthony.chartier@canada.ca>"
        typeset -r description="SQLite User Defined Functions add-on"
    elif [[ "${lib}" = f90sqlite ]]; then
        typeset -r summary="Fortran interface for SQLite"
        typeset -r maintainer="Anthony Chartier <anthony.chartier@canada.ca>"
        typeset -r description="Fortran interface for SQLite"
    else
        die "(build_control_file) This library '${lib}' is not supported!ù"
    fi

        cat <<EOF
{
  "name": "$(echo ${pkgname} | cut -d_ -f1)",
  "package": "${pkgname}",
  "version": "${version}-${compiler}",
  "platform": "${ORDENV_PLAT}",
  "summary": "${summary}",
  "maintainer": "${maintainer}",
  "description": "${description}",
  "build-script": "ssm/package_external_libs from MIDAS",
  "x-build-platform": "${ORDENV_PLAT}",
  "x-build-date": "$(date)",
  "x-build-host": "$(hostname)",
  "x-build-user": "${USER}",
  "x-build-uname": "$(python3 -c 'import os; print(os.uname())')"
}
EOF
} ## End of function 'build_control_file'

load_compiler() {
    ## This function initiliazed the variables 'CLANG_COMPILER' and
    ## 'FORTRAN_COMPILER' which contains the C compiler and Fortran
    ## compiler, respectively.
    typeset -r compiler=${1}

    if [[ "${compiler}" = inteloneapi-2022.1.2 ]]; then
        typeset -r compiler_path=rpn/code-tools/20250925/env/inteloneapi-2022.1.2
        CLANG_COMPILER=icc
        FORTRAN_COMPILER=ifort
    elif [[ "${compiler}" = gnu-14.2.0 || "${compiler}" = gnu-15.1.0 || "${compiler}" = nvhpc-25.3.0 ]]; then
        typeset -r compiler_path=rpn/code-tools/20250804/env/exp/${compiler}
        export MODULEPATH=/home/sidr000/modules:${MODULEPATH}

        if [[ "${compiler}" = nvhpc-25.3.0 ]]; then
            CLANG_COMPILER=nvcc
            FORTRAN_COMPILER=nvfortran
        else
            CLANG_COMPILER=gcc
            FORTRAN_COMPILER=gfortran
        fi
    else
        die "(load_compiler) The compiler '${compiler}' is not supported!"
    fi

    say "... loading ${compiler_path}"
    . r.load.dot ${compiler_path}
} ## End of function 'load_compiler()'


download_lib() {
    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r workdir=${3}

    if [ "${lib}" = hdf5 ]; then
        mkdir ${workdir}/${lib}
        wget --quiet https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5_${version}.zip -O ${workdir}/${lib}/hdf5_${version}.zip
        unzip -q ${workdir}/${lib}/hdf5_${version}.zip -d ${workdir}/${lib}
    elif [ "${lib}" = netcdf-c ]; then
        git clone --config advice.detachedHead=false --branch v${version} https://github.com/Unidata/netcdf-c.git ${workdir}/${lib}/src
    elif [ "${lib}" = netcdf-fortran ]; then
        git clone --config advice.detachedHead=false --branch v${version} https://github.com/Unidata/netcdf-fortran.git ${workdir}/${lib}/src
    elif [ "${lib}" = perftools ]; then
        git clone --config advice.detachedHead=false --branch v${version} git@gitlab.science.gc.ca:perftools/perftools.git ${workdir}/${lib}
    elif [ "${lib}" = udfsqlite ]; then
        git clone --config advice.detachedHead=false --branch ${version} git@gitlab.science.gc.ca:wxobs-libs/libudfsqlite.git ${workdir}/${lib}
    elif [[ "${lib}" = f90sqlite ]]; then
        git clone --config advice.detachedHead=false --branch ${version} git@gitlab.science.gc.ca:wxobs-libs/libf90sqlite.git ${workdir}/${lib}
    else
        die "(download_lib) This library '${lib}' is not supported!ù"
    fi
} ## End of function 'download_lib()'

build_lib() {
    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}
    typeset -r pkgname=${4}
    typeset -r workdir=${5}

    mkdir ${workdir}/${lib}/build
    cd ${workdir}/${lib}/build

    say "(build_lib) Building library '${lib}'"
    if [ "${lib}" = hdf5 ]; then

        ## Setting '-DHDF5_ENABLE_ZLIB_SUPPORT=ON' at the 'cmake' call
        ## generates this warning:
        ##     CMake Warning:
        ##       Manually-specified variables were not used by the project:
        ##
        ##         HDF5_ENABLE_ZLIB_SUPPORT

        cmake -DCMAKE_INSTALL_PREFIX=${workdir}/${pkgname} \
              -DCMAKE_C_COMPILER=${CLANG_COMPILER}         \
              -DHDF5_BUILD_FORTRAN=ON                      \
              -DHDF5_BUILD_CPP_LIB=OFF                     \
              -DDEFAULT_API_VERSION:STRING=v18             \
              -DBUILD_SHARED_LIBS=OFF                      \
              -DHDF5_ENABLE_SZIP_SUPPORT=OFF               \
              ${workdir}/${lib}/hdf5-hdf5_${version}

        make -j install
    elif [ "${lib}" = netcdf-c ]; then
        typeset -r hdf5_version=$(find_version hdf5)
        typeset -r hdf5_ssmpkg=${workdir}/$(package_name hdf5 ${hdf5_version} ${compiler})
        if [[ ! -d "${hdf5_ssmpkg}" ]]; then
           die "(build_lib) To build '${lib}', 'hdf5' must be build first (${hdf5_ssmpkg} not found)"
        fi

        cmake -DCMAKE_BUILD_TYPE=Release                   \
              -DCMAKE_INSTALL_PREFIX=${workdir}/${pkgname} \
              -DCMAKE_C_COMPILER=${CLANG_COMPILER}         \
              -DCMAKE_PREFIX_PATH=${hdf5_ssmpkg}           \
              -DENABLE_NETCDF_4=ON                         \
              -DBUILD_SHARED_LIBS=OFF                      \
              -DCMAKE_EXE_LINKER_FLAGS=-lz                 \
              ${workdir}/${lib}/src

        make -j install

        ## SSM does not recognize 'lib64' so rename it to 'lib'
        mv ${workdir}/${pkgname}/lib64 ${workdir}/${pkgname}/lib
    elif [ "${lib}" = netcdf-fortran ]; then
        typeset -r hdf5_version=$(find_version hdf5)
        typeset -r hdf5_ssmpkg=${workdir}/$(package_name hdf5 ${hdf5_version} ${compiler})
        if [[ ! -d "${hdf5_ssmpkg}" ]]; then
           die "(build_lib) To build '${lib}', 'hdf5' must be build first (${hdf5_ssmpkg} not found)"
        fi

        typeset -r netcdfc_version=$(find_version netcdf-c)
        typeset -r netcdfc_pkgname=$(package_name netcdf-c ${netcdfc_version} ${compiler})
        typeset -r netcdfc_pkgpath=${workdir}/${netcdfc_pkgname}
        typeset -r netcdfc_include=${netcdfc_pkgpath}/include
        typeset -r netcdfc_lib=${netcdfc_pkgpath}/lib/libnetcdf.a
        if [[ ! -d "${netcdfc_include}" ]]; then
           die "(build_lib) To build '${lib}', 'netcdf-c' must be build first (${netcdfc_include} not found)"
        fi
        if [[ ! -f "${netcdfc_lib}" ]]; then
           die "(build_lib) To build '${lib}', 'netcdf-c' must be build first (${netcdfc_lib} not found)"
        fi


        cmake -DCMAKE_BUILD_TYPE=Release                            \
              -DCMAKE_INSTALL_PREFIX=${workdir}/${pkgname}          \
              -DCMAKE_C_COMPILER=${CLANG_COMPILER}                  \
              -DCMAKE_Fortran_COMPILER=${FORTRAN_COMPILER}          \
              -DCMAKE_PREFIX_PATH=${hdf5_ssmpkg}                    \
              -DNETCDF_C_INCLUDE_DIR=${netcdfc_include}             \
              -DNETCDF_C_LIBRARY=${netcdfc_lib}                     \
              -DBUILD_SHARED_LIBS=off                               \
              -DCMAKE_EXE_LINKER_FLAGS='-lcurl -lhdf5 -lhdf5_hl'    \
              ${workdir}/${lib}/src

        make -j install

        ## SSM does not recognize 'lib64' so move its content to 'lib'
        mv ${workdir}/${pkgname}/lib64/* ${workdir}/${pkgname}/lib
    elif [ "${lib}" = perftools ]; then
        cd ${workdir}/${lib}/src/timing
        make lib
        INSTALL_DIR=${workdir}/${pkgname} make install
    elif [ "${lib}" = udfsqlite ]; then
        . r.load.dot eccc/mrd/rpn/libs/20251009-beta

        cd ${workdir}/${lib}/src

        ${CLANG_COMPILER} -o libudfsqlite.a -c udfsqlite.c -DSQLITE_CORE

        mkdir ${workdir}/${pkgname}
        mkdir ${workdir}/${pkgname}/lib
        mv libudfsqlite.a ${workdir}/${pkgname}/lib

        mkdir ${workdir}/${pkgname}/include
        cp udfsqlite.h ${workdir}/${pkgname}/include
    elif [ "${lib}" = f90sqlite ]; then
        typeset -r udfsqlite_version=$(find_version udfsqlite)
        typeset -r udfsqlite_pkgname=$(package_name udfsqlite ${udfsqlite_version} ${compiler})
        typeset -r udfsqlite_include=${workdir}/${udfsqlite_pkgname}/include
        if [[ ! -d "${udfsqlite_include}" ]]; then
           die "(build_lib) To build '${lib}', 'udfsqlite' must be build first (${udfsqlite_include} is not found)"
        fi

        cd ${workdir}/${lib}/src

        ${CLANG_COMPILER}   -o csqlite.o -I${udfsqlite_include} -c csqlite.c
        ${FORTRAN_COMPILER} -o fsqlite.o -c fsqlite.f90
        ar -r libf90sqlite.a csqlite.o fsqlite.o

        mkdir ${workdir}/${pkgname}
        mkdir ${workdir}/${pkgname}/lib
        mv libf90sqlite.a ${workdir}/${pkgname}/lib

        mkdir ${workdir}/${pkgname}/include
        cp *.mod ${workdir}/${pkgname}/include
    else
        die "(build_lib) This library '${lib}' is not supported"
    fi
}

build_ssm_package() {
    set -e

    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}
    typeset -r pkgname=${4}
    typeset -r ssmpkg_destination=${5}
    typeset -r workdir=${6}

    mkdir -p ${workdir}/${pkgname}/.ssm.d
    say "Building the SSM control file"
    build_control_file ${lib} ${version} ${compiler} > ${workdir}/${pkgname}/.ssm.d/control.json

    say "Building the SSM tarball in ${__build_ssmpkg_dir__}"
    cd ${workdir}
    tar cvfzh ${pkgname}.ssm ${pkgname}

    mv ${pkgname}.ssm ${ssmpkg_destination}

    say "The SSM package '${pkgname}.ssm' is available in directory ${ssmpkg_destination}"
    echo
} ## End of function 'build_ssm_package'

find_version() {
    typeset -r lib=${1}

    if [ "${lib}" = hdf5 ]; then
        echo 1.14.6
    elif [ "${lib}" = netcdf-c ]; then
        echo 4.8.1
    elif [ "${lib}" = netcdf-fortran ]; then
        echo 4.6.2
    elif [ "${lib}" = perftools ]; then
        echo 2.1
    elif [ "${lib}" = udfsqlite ]; then
        echo 1.19
    elif [ "${lib}" = f90sqlite ]; then
        echo 1.5
    else
        die "(find_version) This library '${lib}' is not supported"
    fi
} ## End of function 'find_version'

package_name() {
    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}

    echo ${lib}_${version}-${compiler}_${ORDENV_PLAT}
} ## End of function 'package_name'

load_compiler ${compiler}

for lib in ${libs}; do
    version=$(find_version ${lib})
    pkgname=$(package_name ${lib} ${version} ${compiler})

    download_lib      ${lib} ${version} ${workdir}
    build_lib         ${lib} ${version} ${compiler} ${pkgname} ${workdir}
    build_ssm_package ${lib} ${version} ${compiler} ${pkgname} ${ssmpkgdestination} ${workdir}
done

cd
rm -rf ${workdir}
