#!/bin/bash

## This script builds SSM package for external libraries MIDAS needs:
##     f90sqlite
##     udfsqlite
##     perftools

set -e

SECONDS=0

typeset -r scriptName=package_external_libs

function say {
    printf "${scriptName}: ${*}\n"
} ## End of 'function say'

function die {
    say $@ >&2
    exit 1
} ## End of 'function die'

getArg () {
    set -e
    if [ $# -le 1 ]; then
        die "The option '$1' expects an argument"
    fi
    if [[ "$2" == -* ]]; then
        die "The option '$1' expects an argument but have '$2'"
    fi
    echo $2
} ## End of function 'getArg'

args=
while [ $# -gt 0 ]; do
    if [ "${1}" = --libs ]; then
        libs=$(getArg $1 $2)
        shift
    elif [ "${1}" = --compiler ]; then
        compiler=$(getArg $1 $2)
        shift
    elif [ "${1}" = --ssmpkgdestination ]; then
        ssmpkgdestination=$(getArg $1 $2)
        shift
    elif [ "${1}" = --workdir ]; then
        workdir=$(getArg $1 $2)
        shift
    else
        args="${args} ${1}"
    fi
    shift
done

if [ -n "${args}" ]; then
    die "Those arguments '${args}' have not been digested by the option parser"
fi

if [ -z "${libs}" ]; then
    libs="udfsqlite f90sqlite perftools hdf5 netcdf-c netcdf-fortran"
    libs="hdf5 netcdf-c netcdf-fortran"
    #libs=hdf5
    #libs=netcdf-c
fi

for optionarg in libs compiler ssmpkgdestination workdir; do
    eval optionvalue="\${${optionarg}}"
    if [ -z "${optionvalue}" ]; then
        die "The option '--${optionarg}' should be specified and non-empty"
    fi
done

if [[ -d "${workdir}" ]]; then
    die "The workdir directory ${workdir} exists!"
fi
mkdir -p ${workdir}

if [[ ! -d "${ssmpkgdestination}" ]]; then
    say "Creating '${ssmpkgdestination}'"
    mkdir -p ${ssmpkgdestination}
fi

build_control_file() {
    set -e

    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}

    if [[ "${lib}" = hdf5 ]]; then
        typeset -r summary="HDF5 library"
        typeset -r maintainer="MIDAS maintainers"
        typeset -r description="HDF5 is a data model, library, and file format for storing and managing data. It supports an unlimited variety of datatypes, and is designed for flexible and efficient I/O and for high volume and complex data. HDF5 is portable and is extensible, allowing applications to evolve in their use of HDF5. The HDF5 Technology suite includes tools and applications for managing, manipulating, viewing, and analyzing data in the HDF5 format. Please see https://support.hdfgroup.org/HDF5/ for more info."
    elif [[ "${lib}" =~ ^netcdf-.* ]]; then
        typeset -r summary="NetCDF library"
        typeset -r maintainer="MIDAS maintainers"
        typeset -r description="NetCDF (network Common Data Form) is a set of interfaces for array-oriented data access and a freely distributed collection of data access libraries for C, Fortran, C++, Java, and other languages. The netCDF libraries support a machine-independent format for representing scientific data. Together, the interfaces, libraries, and format support the creation, access, and sharing of scientific data. The main Website is: http://www.unidata.ucar.edu/software/netcdf"
    else
        die "(build_control_file) This library '${lib}' is not supported!ù"
    fi

        cat <<EOF
{
  "name": "$(echo ${pkgname} | cut -d_ -f1)",
  "package": "${pkgname}",
  "version": "${version}-${compiler}",
  "summary": "${summary}",
  "maintainer": "${maintainer}",
  "description": "${description}",
  "x-build-platform": "${ORDENV_PLAT}",
  "x-build-date": "$(date)",
  "platform": "${ORDENV_PLAT}",
  "x-build-host": "$(hostname)",
  "x-build-user": "${USER}",
  "x-build-uname": "('Linux', 'inter-nrc-ubuntu2004.science.gc.ca', '5.4.0-96-generic', '#109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022', 'x86_64')",
}
EOF
} ## End of function 'build_control_file'

load_compiler() {
    typeset -r compiler=${1}

    if [ "${compiler}" = inteloneapi-2022.1.2 ]; then
        typeset compiler_path=rpn/code-tools/20250925/env/inteloneapi-2022.1.2
    elif [ "${compiler}" = gnu-14.2.0 -o "${compiler}" = gnu-15.1.0 -o "${compiler}" = nvhpc-25.3.0 ]; then
        typeset compiler_path=rpn/code-tools/20250804/env/exp/${__compiler}
        export MODULEPATH=/home/sidr000/modules:${MODULEPATH}
    else
        die "(load_compiler) The compiler '${compiler}' is not supported!"
    fi

    say "... loading ${compiler_path}"
    . r.load.dot ${compiler_path}
} ## End of function 'load_compiler()'


download_lib() {
    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r workdir=${3}

    if [ "${lib}" = hdf5 ]; then
        mkdir ${workdir}/${lib}
        wget https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5_${version}.zip -O ${workdir}/${lib}/hdf5_${version}.zip
        unzip -q ${workdir}/${lib}/hdf5_${version}.zip -d ${workdir}/${lib}
    elif [ "${lib}" = netcdf-c ]; then
        git clone --config advice.detachedHead=false --branch v${version} https://github.com/Unidata/netcdf-c.git ${workdir}/${lib}/src
    elif [ "${lib}" = netcdf-fortran ]; then
        git clone --config advice.detachedHead=false --branch v${version} https://github.com/Unidata/netcdf-fortran.git ${workdir}/${lib}/src
    else
        die "(download_lib) This library '${lib}' is not supported!ù"
    fi
} ## End of function 'download_lib()'

build_lib() {
    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}
    typeset -r pkgname=${4}
    typeset -r workdir=${5}

    mkdir ${workdir}/${lib}/build
    cd ${workdir}/${lib}/build

    say "(build_lib) Building library '${lib}'"
    if [ "${lib}" = hdf5 ]; then

        ## Setting '-DHDF5_ENABLE_ZLIB_SUPPORT=ON' at the 'cmake' call
        ## generates this warning:
        ##     CMake Warning:
        ##       Manually-specified variables were not used by the project:
        ##
        ##         HDF5_ENABLE_ZLIB_SUPPORT

        cmake -DCMAKE_INSTALL_PREFIX=${workdir}/${pkgname} \
              -DHDF5_BUILD_FORTRAN=ON                      \
              -DHDF5_BUILD_CPP_LIB=OFF                     \
              -DBUILD_SHARED_LIBS=OFF                      \
              -DHDF5_ENABLE_SZIP_SUPPORT=OFF               \
              ${workdir}/${lib}/hdf5-hdf5_${version}

        make -j install
    elif [ "${lib}" = netcdf-c ]; then
        cmake -DCMAKE_INSTALL_PREFIX=${workdir}/${pkgname} \
              -DENABLE_NETCDF_4=ON \
              ${workdir}/${lib}/src

        make -j install
    elif [ "${lib}" = netcdf-fortran ]; then
        typeset -r netcdfc_version=$(find_version netcdf-c)
        typeset -r netcdfc_pkgname=$(package_name netcdf-c ${netcdfc_version} ${compiler})
        typeset -r netcfc_c_include=${workdir}/${netcdfc_pkgname}/include
        typeset -r netcfc_c_lib=${workdir}/${netcdfc_pkgname}/lib64/libnetcdf.so
        if [[ ! -d "${netcfc_c_include}" || ! -f "${netcfc_c_lib}" ]]; then
           die "(build_lib) To build netcdf-fortran you must 'netcdf-c' must be build first"
        fi

        cmake -DCMAKE_INSTALL_PREFIX=${workdir}/${pkgname} \
              -DNETCDF_C_INCLUDE_DIR=${netcfc_c_include}   \
              -DNETCDF_C_LIBRARY=${netcfc_c_lib}           \
              -DBUILD_SHARED_LIBS=off                      \
              ${workdir}/${lib}/src

        make -j install
    else
        die "(build_lib) This library '${lib}' is not supported"
    fi
}

#install_lib() {
#    set -e
#
#    typeset -r __install_builddir__=${1}
#
#    echo ">>> building the install directory for programs on platform ${platform} in ${__install_builddir__}"
#
#    ## install MIDAS programs build with MIDAS fortran modules with prefix 'midas-'
#    for prog in ${midastoplevel}/src/programs/*.f90; do
#        progname=$(basename ${prog} .f90)
#        absname=midas-${progname}_${platform}-${version}.Abs
#        cp ${midasabs}/${absname} ${__install_builddir__}
#        ln -sf ${absname} ${__install_builddir__}/midas-${progname}.Abs
#    done
#
#    ## install MIDAS tools with prefix 'midas.'
#    progname=midas.splitobs
#    cp ${midasabs}/${progname}_${platform}-${version}.Abs ${__install_builddir__}
#    ln -s ${progname}_${platform}-${version}.Abs ${__install_builddir__}/${progname}.Abs
#
#    ## install 'midas-config' script which informs the user about the
#    ## building process
#    cp ${midasabs}/midas-config ${__install_builddir__}
#} ## End of function 'install_lib'

#install_scripts() {
#    set -e
#
#    __install_builddir__=${1}
#
#    echo ">>> building the install directory for scripts in ${__install_builddir__}"
#
#    ## install scripts to be published for 'all' platform
#    for script in ${midastoplevel}/tools/findTrials/midas.findTrials \
#                  ${midastoplevel}/tools/timingTool/midas.timingTool \
#                  ${midastoplevel}/tools/midas_scripts/midas.*; do
#        bscript=$(basename ${script})
#        cp ${script} ${__install_builddir__}/${bscript}_${version}
#        ln -s ${bscript}_${version} ${__install_builddir__}/${bscript}
#    done
#
#    ## The program 'midas.monitor' does not need to be compiled on a specific platform
#    progname=midas.monitor
#    absname=${progname}-${version}.Abs
#    cp ${midasabs}/${absname} ${INSTALL_DIR}
#    ln -sf ${absname} ${INSTALL_DIR}/${progname}.Abs
#
#    unset __install_builddir__
#} ## End of function 'install_scripts'

build_ssm_package() {
    set -e

    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}
    typeset -r pkgname=${4}
    typeset -r ssmpkg_destination=${5}
    typeset -r workdir=${6}

    mkdir -p ${workdir}/${pkgname}/.ssm.d
    say "Building the SSM control file"
    build_control_file ${lib} ${version} ${compiler} > ${workdir}/${pkgname}/.ssm.d/control.json

    say "Building the SSM tarball in ${__build_ssmpkg_dir__}"
    cd ${workdir}
    tar cvfzh ${pkgname}.ssm ${pkgname}

    mv ${pkgname}.ssm ${ssmpkg_destination}

    say "The SSM package '${pkgname}.ssm' is available in directory ${ssmpkg_destination}"
} ## End of function 'build_ssm_package'

find_version() {
    typeset -r lib=${1}

    if [ "${lib}" = hdf5 ]; then
        echo 1.14.6
    elif [ "${lib}" = netcdf-c ]; then
        echo 4.8.1
    elif [ "${lib}" = netcdf-fortran ]; then
        echo 4.6.2
    else
        die "(find_version) This library '${lib}' is not supported!ù"
    fi
} ## End of function 'find_version'

package_name() {
    typeset -r lib=${1}
    typeset -r version=${2}
    typeset -r compiler=${3}

    echo ${lib}_${version}-${compiler}_${ORDENV_PLAT}
} ## End of function 'package_name'

load_compiler ${compiler}

for lib in ${libs}; do
    version=$(find_version ${lib})
    pkgname=$(package_name ${lib} ${version} ${compiler})

    download_lib      ${lib} ${version} ${workdir}
    build_lib         ${lib} ${version} ${compiler} ${pkgname} ${workdir}
    build_ssm_package ${lib} ${version} ${compiler} ${pkgname} ${ssmpkgdestination} ${workdir}
done

cd
rm -r ${workdir}
