#!/bin/bash --login

## This script is supposed to be used by the user who publishes the SSM domain

set -e

echo "Executing: ${0} ${*}"

script=$0

die () {
    set -e
    echo "${script}: ${*}" >&2
    exit 1
}

[ $# -eq 3 ] || die "This tool accepts only three and only three arguments but you gave '${*}'"

product=${1}
[ "${product}" = midas -o "${product}" = verdict ]|| die "The argument can only be 'midas' or 'verdict' but you gave '${product}'"

version=${2}

packages=${3}
[ -d "${packages}" ] || die "Cannot find the directory '${packages}"

command="${HOME}/ssm/${product}/publish --post-install ${HOME}/ssm/${product}/post-install --packages ${packages} --workdir ${HOME}/data_maestro/ords/ssm_tmpdir/midas"
command="${command} --domainpath /fs/ssm/eccc/mrd/rpn/anl/${product}/${version}"
## To test, uncomment this line and comment the line just above
## command="${command} --domainpath ${HOME}/SSM/${product}/${version}"

echo "Launching ${command}"
${command}
